server:
  port: 8080
spring:
  profiles:
    active: dev

---
#开发环境
spring:
  profiles: dev
  application:
    #??????
    name: reggie_take_out
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: localhost
    port: 6379
    database: 0
    client-type: lettuce
    lettuce:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: 1000ms
  cache:
    redis:
      time-to-live: 30M #设置缓存过期时间



mybatis-plus:
  configuration:
    #???????????????????????????????????????
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
reggie:
  path: /Users/zhangtongzheng/Downloads/图片/

---
  #上线环境
  spring:
    profiles: pro
    application:
      #??????
      name: reggie_take_out
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: Ztz0428..
      type: com.alibaba.druid.pool.DruidDataSource
    redis:
      host: 192.168.200.128
      port: 6379
      database: 0
      password: root
    cache:
      redis:
        time-to-live: 30M #设置缓存过期时间
  mybatis-plus:
    configuration:
#下划线转驼峰
      map-underscore-to-camel-case: true
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    global-config:
      db-config:
        id-type: ASSIGN_ID
  reggie:
    path: /usr/local/app/img/